### ISSUE TITLE
Empty results cause an undefined error

### ISSUE THREAD

**Issue by MrFastZombie** [MAPReiff/Steam-Game-Search-NPM#1]
Hey there,

I'm writing a discord bot and I am using this for a game search command. In my testing I noticed that when the results are empty ([Like if your search is Minecraft](https://store.steampowered.com/api/storesearch/?term=minecraft&l=english&cc=US), if you want a good search to test empty results), you get an undefined error, which causes the bot to hang.

`
Exception has occurred: TypeError
TypeError: Cannot read property 'id' of undefined
    at Request._callback (d:\Documents\01_Personal Docs\Personal Programming Projects\BeanBotJS\node_modules\steam-searcher\index.js:42:41)
    at Request.self.callback (d:\Documents\01_Personal Docs\Personal Programming Projects\BeanBotJS\node_modules\request\request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (d:\Documents\01_Personal Docs\Personal Programming Projects\BeanBotJS\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (d:\Documents\01_Personal Docs\Personal Programming Projects\BeanBotJS\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)`

It happens when it tries to run `steamID = res1.items[0].id,`.

I already implemented my own fix for this, but I figured you'd want to know. Here's what I did:

`
            
            
            var res1 = JSON.parse(body)
            if(res1.total == 0) {
                return callback(new Error('No results found.'));
            }

            var steamID = res1.items[0].id,
                reqUrl2 = `http://store.steampowered.com/api/appdetails?appids=${steamID}`

`

**Comment by MAPReiff** [comment]
Thanks for pointing it out... If you make a pull request with the change ill merge it in.

**Comment by MrFastZombie** [comment]
Pull request created, thanks for responding
